apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wrfz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wrfz
    app.kubernetes.io/part-of: tkrw-pr712-0075-0034-app
  name: devfile-sample-wrfz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wrfz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wrfz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-wrfz@sha256:01b29d4c2966a44b7d9e0a1b085d6b206dc3861f12d7d35dd859f2e0f238bfc7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
